waypoint_collector:
  ros__parameters:
    waypoints:

      labels: [
        "west_mid",
        "west_top",
        "north_mid",
        "north_right",
        "east_mid",
        "east_bottom",
        "south_mid",
        "south_left"
      ]

      x: [
        0.0,
        0.0,
        1.0,
        2.0,
        2.0,
        2.0,
        1.0,
        0.0
      ]

      y: [
        2.0,
        4.0,
        4.0,
        4.0,
        2.0,
        0.0,
        0.0,
        0.0
      ]

      yaw: [
        0.0,       # west wall, face into room (+x)
        0.0,

       -1.5708,    # north wall, face into room (-y)
       -1.5708,

        3.1416,    # east wall, face into room (-x)
        3.1416,

        1.5708,    # south wall, face into room (+y)
        1.5708
      ]